---
deployment:
  tasks:
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan migrate --force
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan config:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan config:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan route:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan route:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan view:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan storage:link --force
